### PR TITLE
Bug fix in intermix output test

### PR DESCRIPTION
**Pull request by jmrenouard**

### CODE REVIEW

**Comment by shamrin** [comment]
Thank you!

1. Could you please revert file permission changes for `.travis.yml` and other files?
2. Could you please describe the bug you are trying to fix?

**Comment by jmrenouard** [comment]
Hi @shamrin 

make test

bash test/roundup.sh test/shoreman_test.sh
Shoreman
  it_displays_usage:                               [PASS]
  it_runs_simple_processes:                        [PASS]
  it_passes_environment_variables_to_processes:    [PASS]
  it_supports_dot_env_file:                        [PASS]
  it_can_pass_env_file_as_second_argument:         [PASS]
  it_ignores_comments_in_env_file:                 [PASS]
  it_assigns_a_default_port_number:                [PASS]
  it_allows_overriding_the_port_number:            [PASS]
  it_allows_tabs_in_procfile:                      [PASS]
  it_ignores_comments_in_proc_file:                [PASS]
  it_doesnt_intermix_output:                       [FAIL]
     ./shoreman.sh test/fixtures/fast_procfile
     :
    + output='16:22:14 1        | 1
    16:22:14 1  | '\''echo 1'\'' started with pid 12454
    16:22:14 2  | 2
    16:22:14 2  | '\''echo 2'\'' started with pid 12461
    16:22:14 3  | 3
    16:22:14 3  | '\''echo 3'\'' started with pid 12468
    16:22:14 4  | 4
    16:22:14 4  | '\''echo 4'\'' started with pid 12475
    16:22:14 5  | 5
    16:22:14 5  | '\''echo 5'\'' started with pid 12482
    16:22:14 6  | 6
    16:22:14 6  | '\''echo 6'\'' started with pid 12489
    16:22:14 7  | 7
    16:22:14 7  | '\''echo 7'\'' started with pid 12496
    16:22:14 8  | 8
    16:22:14 8  | '\''echo 8'\'' started with pid 12503'
     echo '16:22:14 1   | 1
    16:22:14 1  | '\''echo 1'\'' started with pid 12454
    16:22:14 2  | 2
    16:22:14 2  | '\''echo 2'\'' started with pid 12461
    16:22:14 3  | 3
    16:22:14 3  | '\''echo 3'\'' started with pid 12468
    16:22:14 4  | 4
    16:22:14 4  | '\''echo 4'\'' started with pid 12475
    16:22:14 5  | 5
    16:22:14 5  | '\''echo 5'\'' started with pid 12482
    16:22:14 6  | 6
    16:22:14 6  | '\''echo 6'\'' started with pid 12489
    16:22:14 7  | 7
    16:22:14 7  | '\''echo 7'\'' started with pid 12496
    16:22:14 8  | 8
    16:22:14 8  | '\''echo 8'\'' started with pid 12503'
     grep -cv '^\d\d:\d\d:\d\d \d\s\|'
    + rc=1
    + set +x
    + bad=0
    exit code 1
  it_can_force_colors_on:                          [PASS]
=========================================================
Tests:   12 | Passed:  11 | Failed:   1
make: *** [test] Error 2

This changes performs a true intermix test:
in the out, test performs:
1° get label only 
1
1
2
2
...
2° uniq -d: try to find all duplicate lines
3° so after this step we must have only 
1
2
3
...
4° if there is 8 lines, it's ok and it's mean that there no intermix lines.

**Comment by jmrenouard** [comment]
Hi @shamrin 

Sorry for my last comment, I can't find out with police appears so huge :)

I have revert permissions.

**Comment by jmrenouard** [comment]
Hi @shamrin 

A other commit is testing if Procfile exists and if not:
Procfile doesn't exist !
and return 1

**Comment by shamrin** [comment]
(I've edited your comment, wrapping nearly everything with triple backticks.)

**Comment by shamrin** [comment]
1. I don't understand why intermix test fails for you. What operating system do you have? The bug could be with shoreman itself (not with shoreman test). Could you please share the output of the following command?

```
env SHOREMAN_COLORS=never ./shoreman.sh test/fixtures/fast_procfile
```

2. While the current intermix test is not ideal, your version doesn't look better to me. By the way, intermix test tries to catch the case where output of concurrent processes go over one another. Take a look at screenshot in PR #37.

3. Current shoreman prints the following error when it can't find the `Procfile`:

```
~/src/shoreman/test (master)> ../shoreman.sh
../shoreman.sh: line 84: Procfile: No such file or directory
```

Your version outputs:

```
~/src/shoreman/test (intermix)> ../shoreman.sh
Procfile doesn't exist !
```

First of all, we've lost an important information here - shoreman script path. Second, what don't you like about the original message? Third, there's a space before the `!`.  If you are interested in a better error message for this case, let's do it in a separate PR and keep the script path.

**Comment by jmrenouard** [comment]
Hi @shamrin 

1° Current Os used is Centos 7 x64

2° Test for intermix is better:
  => Get the output line (16 lines)
  => Grap the proc number
  => based on unsorted list, we try to find all duplicated lines
  => Each proc produces 2 lines, so if there is no intermix, uniq command should return only 8 lines.
In case of intermix line, we should have more than 8 lines which means that proc number is not in a sequential order.

3° Agree with you this commit is actually a regression regarding available information.

**Comment by frdeng** [comment]
It also failed on my RHEL6
I think the better fix is:

$ make
bash test/roundup.sh test/shoreman_test.sh
Shoreman
  it_displays_usage:                               [PASS]
  it_runs_simple_processes:                        [PASS]
  it_passes_environment_variables_to_processes:    [PASS]
  it_supports_dot_env_file:                        [PASS]
  it_can_pass_env_file_as_second_argument:         [PASS]
  it_ignores_comments_in_env_file:                 [PASS]
  it_assigns_a_default_port_number:                [PASS]
  it_allows_overriding_the_port_number:            [PASS]
  it_allows_tabs_in_procfile:                      [PASS]
  it_ignores_comments_in_proc_file:                [PASS]
  it_doesnt_intermix_output:                       [PASS]
  it_can_force_colors_on:                          [PASS]
=========================================================
Tests:   12 | Passed:  12 | Failed:   0
[frdeng@ca-sysinfra604 shoreman]$ 
[frdeng@ca-sysinfra604 shoreman]$ 
[frdeng@ca-sysinfra604 shoreman]$ git diff
diff --git a/test/shoreman_test.sh b/test/shoreman_test.sh
index 4b1ef62..4f048d8 100644
--- a/test/shoreman_test.sh
+++ b/test/shoreman_test.sh
@@ -60,7 +60,7 @@ it_ignores_comments_in_proc_file() {
 
 it_doesnt_intermix_output() {
   output=$(./shoreman.sh 'test/fixtures/fast_procfile'; :)
-  bad=$(echo "$output" | grep -v '^\d\d:\d\d:\d\d \d[[:space:]]|' | wc -l)
+  bad=$(echo "$output" | grep -E -v '^\d\d:\d\d:\d\d \d[[:space:]]|' | wc -l)
   [ $bad -eq 0 ]
 }

**Comment by shamrin** [comment]
@frdeng Cool! Do you prefer to create a separate PR with your change?

**Comment by frdeng** [comment]
No problem, I am working on the PR.

**Comment by shamrin** [comment]
Closed in favour of PR #41.

**Pull request closed without merging**
